USE [master]
GO

/****** Object:  Database [InventoryDatabase]    Script Date: 11/17/2015 11:10:13 AM ******/
CREATE DATABASE [InventoryDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventoryDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\InventoryDatabase.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'InventoryDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\InventoryDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [InventoryDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoryDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoryDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoryDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoryDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoryDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoryDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoryDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoryDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoryDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoryDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoryDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoryDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoryDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoryDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoryDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoryDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoryDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoryDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoryDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoryDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoryDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoryDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [InventoryDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [InventoryDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoryDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventoryDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventoryDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [InventoryDatabase] SET  READ_WRITE 
GO

